package cn.kane.domain;

public class Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listing.LISTING_NUMBER
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    private Integer listingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listing.FIRST_NAME
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listing.LAST_NAME
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listing.EMAIL_ADDRESS
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    private String emailAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listing.LISTING_NUMBER
     *
     * @return the value of listing.LISTING_NUMBER
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public Integer getListingNumber() {
        return listingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listing.LISTING_NUMBER
     *
     * @param listingNumber the value for listing.LISTING_NUMBER
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public void setListingNumber(Integer listingNumber) {
        this.listingNumber = listingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listing.FIRST_NAME
     *
     * @return the value of listing.FIRST_NAME
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listing.FIRST_NAME
     *
     * @param firstName the value for listing.FIRST_NAME
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listing.LAST_NAME
     *
     * @return the value of listing.LAST_NAME
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listing.LAST_NAME
     *
     * @param lastName the value for listing.LAST_NAME
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listing.EMAIL_ADDRESS
     *
     * @return the value of listing.EMAIL_ADDRESS
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listing.EMAIL_ADDRESS
     *
     * @param emailAddress the value for listing.EMAIL_ADDRESS
     *
     * @mbggenerated Sat May 03 21:27:09 CST 2014
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
}